package com.forgekit.runtime.termux

import java.nio.file.Files
import java.nio.file.Path

/**
 * ForgeKit's profile for the interactive terminal shell (never used for plugin jobs).
 *
 * Bash starts with `--rcfile <this file>`, so the load order is:
 *  1. `$PREFIX/etc/bash.bashrc` — Termux defaults, loaded by bash itself;
 *  2. this profile — ForgeKit prompt and color aliases;
 *  3. `~/.bashrc` — the user's own settings, sourced last so they always win.
 *
 * The file lives in ForgeKit's app area (not the Termux prefix), so a runtime repair that
 * re-extracts the prefix never removes it, and it is rewritten whenever its content changes.
 */
public object InteractiveShellProfile {

    public const val FILE_NAME: String = "forgekit.bashrc"

    /** Environment the interactive terminal adds on top of the Termux environment. */
    public val environment: Map<String, String> = mapOf(
        // The renderer draws 24-bit SGR colors; tools like bat, delta and neovim check this.
        "COLORTERM" to "truecolor",
        // BSD-style tools honour this switch for colored output.
        "CLICOLOR" to "1",
    )

    /** The profile text. Colors use ForgeKit's palette: ember path, secondary-grey prompt sign. */
    public fun render(): String = """
        |# ForgeKit interactive shell profile — generated by ForgeKit for every terminal session.
        |# Edits here are overwritten; put your own settings in ~/.bashrc (sourced last, so it wins).

        |# Prompt: ember working directory, grey prompt sign.
        |PS1='\[\e[38;2;255;107;44m\]\w\[\e[0m\] \[\e[38;2;154;166;154m\]\$\[\e[0m\] '

        |# Colored output for the GNU tools shipped in the runtime.
        |alias ls='ls --color=auto'
        |alias grep='grep --color=auto'
        |alias egrep='grep -E --color=auto'
        |alias fgrep='grep -F --color=auto'
        |alias diff='diff --color=auto'

        |[ -r "${'$'}HOME/.bashrc" ] && . "${'$'}HOME/.bashrc"
        |""".trimMargin()

    /** Writes the profile into [directory] when missing or outdated and returns its path. */
    public fun install(directory: Path): Path {
        Files.createDirectories(directory)
        val file = directory.resolve(FILE_NAME)
        val content = render()
        val current = if (Files.isRegularFile(file)) file.toFile().readText() else null
        if (current != content) file.toFile().writeText(content)
        return file
    }
}
